### ISSUE TITLE
Pipe `|` symbol in the path

### ISSUE THREAD

**Issue by gaynetdinov** [ericmj/mint#166] opened 2019-04-25 16:13 UTC
Hi,

I have some problems with sending a request which contains a `|` symbol in the path. Even if I encode such request with `URI.encode` (which would make `|` look like `%7C`) `Mint` refuses to send such request. 

What am I doing wrong? 

Thank you.

**Comment by whatyouhide** [comment] 2019-04-25 16:58
The problem is that we currently don't encode the request path ourselves. If you send a request to `/foo|bar`, you should use `URI.encode/1` on the path first:

```elixir
Mint.request(conn, "GET", URI.encode("/foo|bar"), [])
```

@ericmj we might think about encoding ourselves but at the same time it might break expectations of users. For now I'm going to close this issue as it's easily fixable by calling `URI.encode/1`. Let me know if you still have problems @gaynetdinov! 💟

**Closed by whatyouhide** 2019-04-25 16:58 UTC

**Comment by gaynetdinov** [comment] 2019-04-25 17:25
Ah, `URI.encode` didn't work for me because I was using version 0.1.0. With 0.2.1 everything is okay. Thank you.
